### ISSUE TITLE
`BuiltValueField` is optional

### ISSUE THREAD

**Issue by davidmorgan** [charafau/json2builtvalue#8]
Thanks for the great tool :)

Just one question/observation--the `BuiltValueField` annotation isn't needed, the `wireName` by default is taken directly from the field name--would it make sense to omit it?

**Comment by charafau** [comment]
Hello David! Thanks for mentioning my small tool and thanks for built_value :) 

I know `BuiltValueField` is optional, but I like to clearly specify it in classes, because then I can rename fields without thinking about json structure. I also learned that it's good t have when I was obfuscating code with gson bank on android days. I think I could make some checkbox on top with option but first I need to clean this project a little bit and make deployment easier.

**Comment by davidmorgan** [comment]
Makes sense, thanks :)
